name: Kaggle

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          cache: pip
          python-version: '3.7'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Execute Notebook
        run: jupyter-execute titanic-analysis.ipynb

      - name: Authorize Kaggle
        run: |
          echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}" >> $GITHUB_ENV
          echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}" >> $GITHUB_ENV

      - name: Upload Predictions
        run: kaggle competitions submit -c titanic -f ./kaggle/prediction.csv -m "Submission from GitHub"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Artifact
          path: ./kaggle/prediction.csv